version: "3"
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # qbittorrent Web UI
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8389:8389/udp # Gluetun-Shadowsocks?
      - 8389:8389/tcp # Gluetun-Shadowsocks?
      - 8889:8889/tcp # Gluetun
      - 9696:9696 # prowlarr
      - 9117:9117 # jackett
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 5055:5055 # jellyseer
      - 8096:8096 # jellyfin
      # - 8686:8686 # lidarr
    volumes:
      - /mnt/SSD/portainer/gluetun:/gluetun
      - /mnt/SSD/portainer:/init
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG= /init/$OPENVPN_CUSTOM_CONFIG
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - TZ=Europe/London
    restart: unless-stopped
    network_mode: "bridge"
    dns:
      - 1.1.1.1

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - UMASK=022
      - WEBUI_PORT=8090
    volumes:
      - /mnt/SSD/portainer/qbittorrent/config:/config
      - /mnt/NAS/Media/Downloads:/downloads
      - /mnt/NAS/Media/Movies:/movies
      - /mnt/NAS/Media/Series:/series
      - /mnt/NAS/Media/Music:/music
    network_mode: service:vpn
    labels:
      - autoheal=true
    healthcheck:
      test: curl google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  prowlarr:
    image: hotio/prowlarr:testing
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=GB
    volumes:
      - /mnt/SSD/portainer/prowlarr:/config
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
      - qbittorrent

  jackett:
    image: linuxserver/jackett:latest
    container_name: vpn-jackett
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /mnt/SSD/portainer/jackett/config:/config
    network_mode: service:vpn
    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.depends-on=vpn
    healthcheck:
      test: curl google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/SSD/portainer/sonarr/config:/config
      - /mnt/NAS/Media/Series:/series
      - /mnt/NAS/Media/Downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - jackett
      - qbittorrent

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/SSD/portainer/radarr3/config:/config
      - /mnt/NAS/Media/Movies:/movies
      - /mnt/NAS/Media/Downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - jackett
      - qbittorrent

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /mnt/SSD/portainer/jellyfin/config:/config
      - /mnt/NAS/Media/Movies:/movies
      - /mnt/NAS/Media/Series:/series
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - UMASK=022
    restart: unless-stopped
    network_mode: service:vpn
